
import java.sql.*;
import javax.swing.*;
import project.connectionpro;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author arkap
 */
public class Returnbook extends javax.swing.JFrame {

    /**
     * Creates new form Returnbook
     */
    public Returnbook() {
        initComponents();
        setSize(551, 393);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Book ID");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 93, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Student ID");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 139, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Issue Date");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 183, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Due Date");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 214, -1, 24));

        jTextField2.setBackground(new java.awt.Color(255, 232, 140));
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(226, 139, 181, -1));

        jButton1.setBackground(new java.awt.Color(255, 232, 140));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("RETURN");
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.lightGray, null, null));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(226, 267, -1, -1));

        jButton2.setBackground(new java.awt.Color(255, 232, 140));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("CANCEL");
        jButton2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.lightGray, null, null));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(326, 267, -1, -1));

        jTextField3.setBackground(new java.awt.Color(255, 232, 140));
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(226, 183, 181, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Book Return");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, 136, 28));

        jTextField1.setBackground(new java.awt.Color(255, 232, 140));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(226, 93, 181, -1));

        jTextField4.setBackground(new java.awt.Color(255, 232, 140));
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(226, 218, 181, -1));

        jButton3.setBackground(new java.awt.Color(255, 232, 140));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setText("SEARCH");
        jButton3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.lightGray, null, null));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(425, 136, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        setVisible(false);
        new home().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int num=0;
        String bookID=jTextField1.getText();
       String studentID=jTextField2.getText();
    
       
       try{
           //A Connection is the session between java application and database
            Connection con=connectionpro.getCon();
            //The Statement interface provides methods to execute queries with the database.
            Statement st= con.createStatement();
            //The object of ResultSet maintains a cursor pointing to a row of a table. Initially, cursor points to before the first row.
            ResultSet rsp=st.executeQuery("select number from book where bookID='"+bookID+"'");
            if(rsp.next()){
            num=rsp.getInt("number");
            }
            st.executeUpdate("update issue set returnBook='Yes' where bookID='"+bookID+"' and studentID='"+studentID+"'");
            num++;
            st.executeUpdate("update book set number='"+num+"' where bookID='"+bookID+"'");
            JOptionPane.showMessageDialog(null,"Successfully Returned");
            setVisible(false);
            new Returnbook().setVisible(true);
            
       }
       catch(Exception e){
           JOptionPane.showMessageDialog(null,"Connection Error......");
           setVisible(false);
           new Returnbook().setVisible(true);
       }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
       
       String bookID=jTextField1.getText();
       String studentID=jTextField2.getText();
    
       
       try{
           //A Connection is the session between java application and database
            Connection con=connectionpro.getCon();
            //The Statement interface provides methods to execute queries with the database.
            Statement st= con.createStatement();
            //The object of ResultSet maintains a cursor pointing to a row of a table. Initially, cursor points to before the first row.
 
            ResultSet rs=st.executeQuery("select * from issue where bookID='"+bookID+"' and studentID='"+studentID+"'");                
            if(rs.next()){
               jTextField3.setText(rs.getString(3));
               jTextField4.setText(rs.getString(4));
                //user can't modify it
               jTextField1.setEditable(false);
               jTextField2.setEditable(false);
         
            }
            else{
                JOptionPane.showMessageDialog(null,"Book is not Issued for this Student Id");
                setVisible(false);
                 new Returnbook().setVisible(true);
            }
       }
       catch(Exception e){
           JOptionPane.showMessageDialog(null,"Connection Error......");
       }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Returnbook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Returnbook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Returnbook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Returnbook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Returnbook().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
